---
abstract: 'Plugin Bundle for distributions built by GTERMARS'
author:
  - 'Graham TerMarsch <cpan@howlingfrog.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::DiagINC: '0.002'
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-GTERMARS
no_index:
  directory:
    - t
    - xt
requires:
  Dist::Zilla: '6.005'
  Dist::Zilla::Plugin::Bootstrap::lib: '1.001002'
  Dist::Zilla::Plugin::BumpVersionAfterRelease: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::EnsureChangesHasContent: '0'
  Dist::Zilla::Plugin::EnsureMinimumPerl: '0'
  Dist::Zilla::Plugin::Git: '2.046'
  Dist::Zilla::Plugin::GitHub: '0.46'
  Dist::Zilla::Plugin::GitHub::RequireGreenBuild: '0'
  Dist::Zilla::Plugin::Prereqs::AuthorDeps: '0.006'
  Dist::Zilla::Plugin::Prereqs::FromCPANfile: '0.08'
  Dist::Zilla::Plugin::PromptIfStale: '0.057'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.163250'
  Dist::Zilla::Plugin::RunExtraTests: '0.028'
  Dist::Zilla::Plugin::StaticInstall: '0.012'
  Dist::Zilla::Plugin::Test::CleanNamespaces: '0'
  Dist::Zilla::Plugin::Test::Compile: '0'
  Dist::Zilla::Plugin::Test::DiagINC: '0'
  Dist::Zilla::Plugin::Test::EOF: '0.0600'
  Dist::Zilla::Plugin::Test::EOL: '0.19'
  Dist::Zilla::Plugin::Test::Kwalitee: '2.12'
  Dist::Zilla::Plugin::Test::MinimumVersion: '2.000010'
  Dist::Zilla::Plugin::Test::NoBreakpoints: v0.0.2
  Dist::Zilla::Plugin::Test::NoTabs: '0.15'
  Dist::Zilla::Plugin::Test::PodSpelling: '2.007005'
  Dist::Zilla::Plugin::Test::ReportPrereqs: '0.027'
  Dist::Zilla::Plugin::Test::Synopsis: '2.000007'
  Dist::Zilla::Plugin::Test::UnusedVars: '2.000007'
  Dist::Zilla::PluginBundle::Git::CheckFor: '0.014'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  namespace::autoclean: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/bleargh45/Dist-Zilla-PluginBundle-Author-GTERMARS/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-Author-GTERMARS/
  repository: git://github.com/bleargh45/Dist-Zilla-PluginBundle-Author-GTERMARS.git
version: '0.05'
x_generated_by_perl: v5.32.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: Artistic-2.0
x_static_install: 1
